[workspace]
members = [
  "xee",
  "xee-xpath",
  "xee-qt",
  "xee-xpath-ast",
  "xee-xpath-macros",
  "xee-schema-type",
  "xee-xslt-ast",
  "xee-xpath-outer",
]
# even if all crates are set to edition 2021, we still need to force the
# resolver to 2
# https://github.com/gfx-rs/wgpu/issues/2356#issuecomment-1005134986
resolver = "2"

[workspace.dependencies]
ahash = "0.8.6"
strum = "0.25"
strum_macros = "0.25"
xot = "0.18.0"
clap = "4.2.7"
ibig = "0.3.6"
ordered-float = "3.7.0"
rust_decimal = "1.30.0"
chumsky = { git = "https://github.com/zesterer/chumsky.git" }
#  "1.0.0-alpha.4"
icu = "1.2.0"
serde = "1"
chrono = "0.4.30"
blanket = "0.2.0"

[profile.test.package.xot]
opt-level = 3
