[workspace]
members = [
  "xee",
  "xee-xpath",
  "xee-qt",
  "xee-xpath-ast",
  "xee-xpath-macros",
  "xee-schematype",
]
# even if all crates are set to edition 2021, we still need to force the
# resolver to 2
# https://github.com/gfx-rs/wgpu/issues/2356#issuecomment-1005134986
resolver = "2"

[workspace.dependencies]
xot = "0.13.2"
miette = "5.8.0"
clap = "4.2.7"

[profile.test.package.xot]
opt-level = 3
