[workspace]
members = [
  "xee",
  "xee-xpath",
  "xee-qt",
  "xee-xpath-ast",
  "xee-xpath-macros",
  "xee-schema-type",
]
# even if all crates are set to edition 2021, we still need to force the
# resolver to 2
# https://github.com/gfx-rs/wgpu/issues/2356#issuecomment-1005134986
resolver = "2"

[workspace.dependencies]
xot = "0.16.0"
miette = "5.8.0"
clap = "4.2.7"
ibig = "0.3.6"
ordered-float = "3.7.0"
rust_decimal = "1.30.0"
chumsky = "1.0.0-alpha.4"
icu = "1.2.0"
serde = "1"

[profile.test.package.xot]
opt-level = 3
