[package]
name = "xee-xslt-ast"
version = "0.1.0"
edition = "2021"
authors = [
    "Martijn Faassen <faassen@startifact.com>",
    "Nalle Rooth <nalle.rooth@paligo.net>",
]
keywords = ["xml", "xslt"]
license = "Apache-2.0"
description = "XSLT parser and AST implementation"
repository = "http://github.com/Paligo/xee"
readme = "README.md"
documentation = "https://docs.rs/xee-xslt"
homepage = "https://github.com/Paligo/xee-xslt"

[features]
serde = ["dep:serde", "xee-xpath-ast/serde"]

[dependencies]
ahash = "0.8.3"
xee-xpath-ast = { path = "../xee-xpath-ast" }
thiserror = "1.0.40"
xot = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
strum = "0.25"
strum_macros = "0.25"

[dev-dependencies]
xee-xslt-ast = { path = ".", features = ["serde"] }
insta = { version = "1.29.0", features = ["ron", "glob"] }
xot = { workspace = true, features = ["proptest"] }
ron = "0.8.0"
