[package]
name = "xee-xpath-ast"
version = "0.1.0"
edition = "2021"
authors = ["Martijn Faassen <faassen@startifact.com>"]
keywords = ["xml", "xpath"]
license = "Apache-2.0"
description = "XPath parser and AST implementation"
repository = "http://github.com/Paligo/xee"
readme = "README.md"
documentation = "https://docs.rs/xee-xpath"
homepage = "https://github.com/Paligo/xee-xpath"

[dependencies]
ahash = "0.8.3"
chumsky = { workspace = true }
logos = "0.13.0"
blanket = "0.2.0"
thiserror = "1.0.40"
ordered-float = { workspace = true }
ibig = { workspace = true }
rust_decimal = { workspace = true }
xot = { workspace = true }

[dev-dependencies]
ibig = { workspace = true, features = ["serde"] }
ordered-float = { workspace = true, features = ["serde"] }
insta = { version = "1.29.0", features = ["ron", "glob"] }
xot = { workspace = true, features = ["proptest"] }
rust_decimal_macros = "1.29.1"
ron = "0.8.0"
serde = { workspace = true, features = ["derive"] }
