[package]
name = "xee-xpath"
version = "0.1.0"
edition = "2021"
authors = ["Martijn Faassen <faassen@startifact.com>"]
keywords = ["xml", "xpath"]
license = "Apache-2.0"
description = "XPath implementation"
repository = "http://github.com/Paligo/xee"
readme = "README.md"
documentation = "https://docs.rs/xee-xpath"
homepage = "https://github.com/Paligo/xee-xpath"

[dependencies]
ahash = "0.8.3"
miette = "5.8.0"
next-gen = "0.1.1"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
ordered-float = "3.6.0"
pest = "2.5.6"
pest_derive = "2.5.6"
thiserror = "1.0.40"
xot = { workspace = true }

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml", "glob"] }
rstest = "0.16.0"
test-generator = "0.3.0"
xot = { workspace = true, features = ["proptest"] }
