[package]
name = "xee-xpath"
version = "0.1.0"
edition = "2021"
authors = ["Martijn Faassen <faassen@startifact.com>"]
keywords = ["xml", "xpath"]
license = "Apache-2.0"
description = "XPath implementation"
repository = "http://github.com/Paligo/xee"
readme = "README.md"
documentation = "https://docs.rs/xee-xpath"
homepage = "https://github.com/Paligo/xee-xpath"

[features]
serde = [
    "dep:serde",
    "ibig/serde",
    "ordered-float/serde",
    "xee-schema-type/serde",
    "xee-xpath-ast/serde",
    "chumsky/serde",
]

[dependencies]
ahash = { workspace = true }
arrayvec = "0.7.2"
chumsky = { workspace = true }
next-gen = "0.1.1"
strum = { workspace = true }
strum_macros = { workspace = true }
nonempty = "0.8.1"
num = "0.4.1"
num-derive = "0.4.1"
num-traits = "0.2.17"
ordered-float = "3.6.0"
rust_decimal = "1.30.0"
thiserror = "1.0.40"
xot = { workspace = true }
xee-xpath-ast = { path = "../xee-xpath-ast" }
xee-xpath-macros = { path = "../xee-xpath-macros" }
xee-schema-type = { path = "../xee-schema-type" }
lexical = { version = "6.1.1", features = ["format"] }
ibig = "0.3.6"
regex = "1.9.3"
hex = "0.4.3"
base64 = "0.21.2"
chrono = { workspace = true }
icu = { workspace = true, features = ["serde"] }
icu_provider_adapters = { version = "1.2.0", features = ["serde"] }
icu_provider_blob = "1.2"
serde-querystring = "0.2.1"
serde = { workspace = true, features = ["derive"], optional = true }
url = "2.4.1"
fancy-regex = "0.11.0"

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml", "glob"] }
rstest = "0.16.0"
test-generator = "0.3.0"
xot = { workspace = true, features = ["proptest"] }
rust_decimal_macros = "1.29.1"
